Class {
	#name : 'KTLModel',
	#superclass : 'MooseModel',
	#traits : 'KTLTEntityCreator',
	#classTraits : 'KTLTEntityCreator classTrait',
	#category : 'Katalon-Model-Model',
	#package : 'Katalon-Model',
	#tag : 'Model'
}

{ #category : 'accessing' }
KTLModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query')
]

{ #category : 'meta' }
KTLModel class >> annotation [
	<FMClass: #KTLModel super: #MooseModel>
	<package: #'Katalon-Model'>
	<generated>
]
